name: Sync to Professor Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to professor repo
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync@github.com"
          
          git remote add professor https://x-access-token:${{ secrets.PROFESSOR_TOKEN }}@github.com/cpit252-spring-26-IT1/BaseNode.git
          
          git push professor main
